# Generated by Django 5.2.6 on 2025-09-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('cliente_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=15)),
                ('telemovel', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('morada', models.CharField(max_length=50)),
                ('nif', models.IntegerField(db_column='NIF', unique=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Faturas_Pagamentos',
            fields=[
                ('fatura_id', models.IntegerField(primary_key=True, serialize=False)),
                ('data_emissao', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pagamento', models.CharField(max_length=20)),
                ('status_pagamento', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'faturas_pagamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('funcionario_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=15)),
                ('cargo', models.CharField(max_length=20)),
                ('telemovel', models.IntegerField()),
                ('morada', models.CharField(max_length=20)),
                ('especialidade', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'funcionario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Itens_Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('preco_unitairo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'itens_servico_os',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('os_id', models.IntegerField(primary_key=True, serialize=False)),
                ('data_abertura', models.DateField()),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('descricao_problema', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'ordens_servico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pecas',
            fields=[
                ('peca_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=15)),
                ('descricao', models.CharField(max_length=100)),
                ('preco', models.DecimalField(db_column='preco_unitario', decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
            ],
            options={
                'db_table': 'pecas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pecas_Usadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'pecas_usadas_os',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('servico_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=15)),
                ('descricao', models.CharField(max_length=150)),
                ('preco_base', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'servico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('veiculo_id', models.IntegerField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=15)),
                ('modelo', models.CharField(max_length=15)),
                ('matricula', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'veiculo',
                'managed': False,
            },
        ),
    ]
