# Generated by Django 5.2.6 on 2025-09-26 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabproject28335', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='veiculo',
            table='veiculos',
        ),
    ]
