# Generated by Django 5.2.6 on 2026-02-02 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabproject28335', '0002_alter_veiculo_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='funcionario',
            table='funcionarios',
        ),
    ]
