# Generated by Django 4.1.4 on 2023-01-11 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cineapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
